import { createFileRoute, Link } from "@tanstack/react-router";
import { PublicNav } from "@/components/PublicNav";
import { Sparkles, Users, Store, School, Heart } from "lucide-react";

export const Route = createFileRoute("/about")({
  head: () => ({
    meta: [
      { title: "About — EduKart" },
      { name: "description", content: "EduKart is the AI-powered school marketplace connecting schools, parents and vendors." },
    ],
  }),
  component: About,
});

function About() {
  return (
    <div className="min-h-screen bg-background">
      <PublicNav />
      <main className="mx-auto max-w-5xl px-4 py-12 sm:px-6">
        <span className="inline-flex items-center gap-2 rounded-full bg-white/70 px-3 py-1 text-xs font-semibold text-foreground shadow-[var(--shadow-soft)] backdrop-blur">
          <Sparkles className="h-3.5 w-3.5" /> Our story
        </span>
        <h1 className="mt-4 font-display text-4xl font-bold sm:text-5xl">Back-to-school, reimagined.</h1>
        <p className="mt-4 max-w-2xl text-base text-muted-foreground sm:text-lg">
          EduKart was built to remove the chaos of school season. Schools share their official booklists, vendors list verified products, and parents get the perfect kit — generated by AI, delivered to their door.
        </p>

        <div className="mt-12 grid gap-5 md:grid-cols-3">
          {[
            { i: <School className="h-6 w-6" />, t: "2,400+ Schools", s: "Verified institutions across India trust EduKart for booklists and kits.", g: "var(--gradient-leaf)" },
            { i: <Users className="h-6 w-6" />, t: "180K+ Parents", s: "Saving hours and rupees every back-to-school season.", g: "var(--gradient-sky)" },
            { i: <Store className="h-6 w-6" />, t: "5,000+ Vendors", s: "Local & national vendors growing their stores with us.", g: "var(--gradient-tangerine)" },
          ].map((s) => (
            <div key={s.t} className="rounded-3xl glass-card p-6">
              <div className="grid h-12 w-12 place-items-center rounded-2xl text-white shadow-[var(--shadow-soft)]" style={{ background: s.g }}>{s.i}</div>
              <h3 className="mt-4 font-display text-lg font-bold">{s.t}</h3>
              <p className="mt-1 text-sm text-muted-foreground">{s.s}</p>
            </div>
          ))}
        </div>

        <section className="mt-16 rounded-3xl glass-card p-8 sm:p-10">
          <div className="flex items-center gap-2 text-xs font-bold uppercase tracking-widest text-muted-foreground">
            <Heart className="h-3.5 w-3.5" /> Our mission
          </div>
          <h2 className="mt-3 font-display text-2xl font-bold sm:text-3xl">
            Make every back-to-school season effortless, affordable and joyful.
          </h2>
          <p className="mt-3 text-muted-foreground">
            We're building the trust layer between schools, parents and vendors — so every child gets exactly what they need to learn, and every business gets paid fairly.
          </p>
          <div className="mt-6 flex flex-wrap gap-3">
            <Link to="/marketplace" className="rounded-full bg-foreground px-5 py-2.5 text-sm font-semibold text-background hover:scale-105">Explore marketplace</Link>
            <Link to="/contact" className="rounded-full border border-border bg-white/70 px-5 py-2.5 text-sm font-semibold text-foreground hover:bg-white">Contact us</Link>
          </div>
        </section>
      </main>
    </div>
  );
}
